FROM node:18.18.2-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

ENV NODE_ENV=staging
ENV REACT_APP_API_URL=http://localhost:3333

# Copiar os arquivos de package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Copiar o código-fonte para o diretório de trabalho
COPY . .

# Instalar as dependências do projeto
RUN npm install

# Expor a porta 3000 para acesso ao servidor de desenvolvimento
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "start"]
