version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: reactjs-boilerplate
    environment:
      - NODE_ENV=staging
      - REACT_APP_API_URL=http://localhost:3333
    volumes:
      - .:/app
      - /app/node_modules
